# Generated by Django 4.1.2 on 2022-10-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_you',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='previous_work',
        ),
    ]
